name: Run Monitoring Checks

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check LMS Services
      run: |
        response=$(curl -s -w "\n%{http_code}" -X POST https://lms-monitor-api.vercel.app/api/safe-check \
          -H "Authorization: Bearer ${{ secrets.MONITORING_API_KEY }}")
        
        http_code=$(echo "$response" | tail -n 1)
        body=$(echo "$response" | head -n -1)
        
        echo "HTTP Status: $http_code"
        echo "Response: $body"
        
        if [ "$http_code" != "200" ]; then
          echo "Monitoring check failed with status $http_code"
          exit 1
        fi
        
    - name: Get Status Summary
      run: |
        echo "Fetching current status..."
        curl -s https://lms-monitor-api.vercel.app/api/status | jq '.services[] | "\(.name): \(.status)"'